### ISSUE TITLE
API version is [1,22] in Panpipe version "0.2"

### ISSUE THREAD

**Issue by dompdv** [marcelotto/panpipe#5]
Hello, (and many thanks for this nice library).
I'm using the latest version of pandoc and I ran into issues around the fact that encoding and decoding version of pandoc are different. 

I solved this by changing the @api_version in module Panpipe.Pandoc to [1,23], which is an ugly way to solve the problem.

(I saw that this change has been done in the repo, after the release of the 0.2.0 version)

I must admit that, as I'm totally new to this Pandoc universe, this is a little bit like black magic. 

Is there a way  to set Panpipe's Pandoc API version nicely ?

**Comment by marcelotto** [comment]
Hi.

> Is there a way to set Panpipe's Pandoc API version nicely?

No, and it wouldn't make sense. The Pandoc API version is the version of the internal Pandoc AST and since Panpipe is a wrapper around this Pandoc AST it is bound to this. Whenever this Pandoc API version changes (which happens less frequently than regular Pandoc versions), a new Panpipe version is needed to adapt to these changes. 

I've just released Panpipe v0.3 which adapts to the new API version (that came with Pandoc 3.0).

**Comment by dompdv** [comment]
Wonderful, thanks
